frontend/Dockerfile, frontend/nginx.conf
remove `X-Frame-Options` header to allow embedding recosante widget
=> fix(frontend): custom nginx.conf for headers

frontend/content/pages/accessibilite.md, frontend/content/pages/mentions-legales.md, frontend/src/components/layout/footer/Links.js
Ajout de la declaration d'accessibilité à jour
=> fix: ajout declaration a11y

.kontinuous/config.yaml, README.md
Corrige un probleme que j'avais introduit dans ma PR pour les envs de review. (nom du secret de DB)
=> fix(ci): db admin secret

.github/workflows/release.yml, .github/workflows/test.yaml, .gitignore, api/.env.example, api/README.md, api/package.json, docker-compose.yml, package.json
Cette PR ajoute une task Tests aux github actions
=> feat(test): play them on ci

api/ecosante/celery_worker.py, api/wsgi.py, libs/indice_pollution/indice_pollution/celery_worker.py
Reduce sentry performance sampleRate
=> fix(sentry): reduce sampleRate

api-node/package.json, api-node/prisma/migrations/20240103165111_indice_uv/migration.sql, api-node/prisma/migrations/20240103170317_indicator_name/migration.sql, api-node/prisma/schema.prisma, api-node/prisma/seed/indicators.ts, api-node/src/controllers/indicator.ts, api-node/src/index.ts, expo-app/src/scenes/onboarding-geolocation.tsx
Create indicators model / add script to seed / add endpoints to get all indicators list
=> feat: Create indicators model / add script to seed / add endpoints to get all indicators list

expo-app/app.json, expo-app/src/scenes/onboarding/screens/screen_5.tsx, expo-app/src/services/commune.ts, expo-app/src/services/expo-push-notifs.tsx, expo-app/src/services/logEventsWithMatomo.ts
feat: Add EAS project ID to app.json and update push notification handling
=> feat: Add EAS project ID to app.json and update push notification handling

expo-app/src/assets/icons/arrow.tsx, expo-app/src/constants/notification.ts, expo-app/src/navigators.tsx, expo-app/src/scenes/dashboard/dashboard.tsx, expo-app/src/scenes/settings/notifications-list.tsx, expo-app/src/scenes/settings/settings.tsx, expo-app/src/scenes/share.tsx, expo-app/src/types/notification.ts, expo-app/src/zustand/notification/useNotification.ts
Add SettingsPage component and update styling in navigators and dashboard
=> Add SettingsPage component and update styling in navigators and dashboard

api-node/src/aggregators/atmo.ts, api-node/src/index.ts
Formating data after multiple fetch in atmo indice, still lot of format pb
=> Formating data after multiple fetch in atmo indice, still lot of format pb

expo-app/package-lock.json, expo-app/package.json, expo-app/src/components/indicators/graphs/line.tsx, expo-app/src/components/indicators/indicator-preview.tsx, expo-app/src/components/indicators/mocks/fake.ts, expo-app/yarn.lock
Add fake data to generate different indicator in front
=>  feat(indicator) : Add fake data to generate different indicator in front

api-node/prisma/schema.prisma, api-node/src/controllers/indicator.ts
pareil un `npm run prisma-reset-db` fait du bien
après j'arrête !
=> fix: liste des indices

expo-app/app.json, expo-app/eas.json, expo-app/src/assets/icons/close.tsx, expo-app/src/components/indicators/indicator-preview.tsx, expo-app/src/components/indicators/indicators-selector.tsx, expo-app/src/scenes/dashboard/dashboard.tsx, expo-app/src/scenes/dashboard/indicator-detail.tsx, expo-app/src/scenes/dashboard/indicator-selector-sheet.tsx, expo-app/src/scenes/dashboard/indicators-list-preview.tsx, expo-app/src/zustand/indicator/useIndicator.ts
https://github.com/SocialGouv/recosante/assets/4417717/7878e92a-1f9f-4f64-a047-171f5d5217c0
=> feat(indicator): Add indicator detail page / add logic / add zustand / add bottom sheet

api-node/prisma/schema.prisma, api-node/src/aggregators/indice_uv.ts, api-node/src/controllers/indice_uv.ts, api-node/src/index.ts, api-node/src/middlewares/errors.ts, api-node/src/types/api/indice_uv.ts, api-node/src/utils/indice_uv.ts
questions en suspens: 
- le modèle de retour est-il cool ? ou à améliorer ?
- faut-il requêter par insee code + date ? ou matomo id ? on pourra régler cette question plus tard, c'est pas bloquant
l'important ici, c'est surtout le modèle de retour
=> feat: uv api flow

expo-app/get-ip.sh, expo-app/package.json, expo-app/src/config.ts
si c'est pas clair comme de l'eau de roche, dis-moi - faut que je document un peu plus peut-être
=> fix: api and local ip

expo-app/package-lock.json, expo-app/package.json, expo-app/src/scenes/dashboard/indicators-list-preview.tsx, expo-app/yarn.lock
[…](feat: Add @react-navigation/material-top-tabs package and refactor IndicatorsListPreview component)
=> feat: Add @react-navigation/material-top-tabs package and refactor IndicatorsListPreview component

api-node/src/controllers/environment.ts, api-node/src/controllers/user.ts, api-node/src/index.ts
à tester avec https://github.com/SocialGouv/recosante-expo-app/pull/11
objectifs: 
- avoir la possibilité d'un vrai environnement de préprod/test sur testflight
- pouvoir switcher d'env selon la version de l'app, et donc basculer en prod une version testflight testée et approuvée
=> feat: api environment

.prettierignore, api-node/.prettierignore, api-node/prisma/migrations/20240201145701_add_feedback_model/migration.sql, api-node/prisma/schema.prisma, api-node/src/controllers/feedback.ts, api-node/src/controllers/mail.ts
Allow user to send feedback.
Save on db / Send email to the staff.
=> feat(feedback): Save feedback in Db + sendMail when receive new one

api-node/data/about/indice_atmo.md
=> fix: sub and sup for indice atmo about

api-node/src/controllers/call-to-action.ts, api-node/src/index.ts
=> feat(cta): add new call-to-action controllers for managing call to action in dashboard page

.kontinuous/env/prod/values.yaml
=> fix:recosante-update-resources

api-node/data/about/pollens.md
=> fix: pollens-typo

api-node/src/cronjobs/cleaning.ts
- Added console logs to track the start and end of the cleaning process.
- Included detailed logs for each data type cleaned, showing the count of deleted entries.
- Introduced a summary of total entries deleted and the duration of the cleaning operation.
- Updated the initialization log for the cron job to provide clearer information.
=> feat: enhance data cleaning process with detailed logging and summary
